application: moegirlweixin
version: 2beta
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /weixin
  script: mainProcessor.app
- url: /test
  script: tester.app
- url: /init
  script: inits.app
- url: /page
  static_dir: page
- url: /
  static_files: page/index.html
  upload: page/index.html